### ISSUE TITLE
Trace plots for integer variables cannot be shown

### ISSUE THREAD

**Issue by bredelings** [beast-dev/tracer#105]
[C1.log](https://github.com/beast-dev/tracer/files/1454060/C1.log)

Hi, I assume this is in-progress, but in case its useful, I tried it out, and it seems that trace plots for integer variables are currently broken.  However, you can get them to display if you select one real variable along with integer variables.

Here is a (possibly related) stack trace:
Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
	at dr.app.gui.chart.FrequencyPlot.getDiscreteFrequencyDistribution(Unknown Source)
	at dr.app.gui.chart.CategoryDensityPlot.setData(Unknown Source)
	at dr.app.gui.chart.CategoryDensityPlot.<init>(Unknown Source)
	at tracer.traces.DiscreteDensityPanel.setupTraces(Unknown Source)
	at tracer.traces.DiscreteDensityPanel.setTraces(Unknown Source)
	at tracer.traces.DensityPanel.setTraces(Unknown Source)
	at tracer.traces.TracePanel.setTraces(Unknown Source)
	at tracer.application.TracerFrame.statisticTableSelectionChanged(Unknown Source)
	at tracer.application.TracerFrame$4.valueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:154)
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:685)
	at javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(BasicTableUI.java:953)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(BasicTableUI.java:1166)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by rambaut** [comment]
Working.

**Comment by bredelings** [comment]
This still doesn't work for me.
% javac -version
javac 1.8.0_151
% uname -a
Linux telomere 4.14.0-rc7-amd64 #1 SMP Debian 4.14~rc7-1~exp1 (2017-10-30) x86_64 GNU/Linux
% ant linux
Buildfile: /home/bredelings/Devel/tracer/build.xml

init:

compile:
    [javac] /home/bredelings/Devel/tracer/build.xml:54: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds

dist:
      [jar] Building jar: /home/bredelings/Devel/tracer/build/dist/tracer.jar

linux:
   [delete] Deleting directory /home/bredelings/Devel/tracer/release/Linux/Tracer_v1.7-Pre20170916
    [mkdir] Created dir: /home/bredelings/Devel/tracer/release/Linux/Tracer_v1.7-Pre20170916
     [copy] Copying 1 file to /home/bredelings/Devel/tracer/release/Linux/Tracer_v1.7-Pre20170916/bin
     [copy] Copying 1 file to /home/bredelings/Devel/tracer/release/Linux/Tracer_v1.7-Pre20170916/images
     [copy] Copying 1 file to /home/bredelings/Devel/tracer/release/Linux/Tracer_v1.7-Pre20170916/lib
     [copy] Copying 1 file to /home/bredelings/Devel/tracer/release/Linux/Tracer_v1.7-Pre20170916
      [tar] Building tar: /home/bredelings/Devel/tracer/release/Tracer_v1.7-Pre20170916.tgz
     [echo] Linux/Unix version release is finished.

BUILD SUCCESSFUL
Total time: 2 seconds
% tracer C1.log
[select Trace tab]
[select '#indels1' -> the trace plot doesn't change]
Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
	at dr.app.gui.chart.FrequencyPlot.getDiscreteFrequencyDistribution(Unknown Source)
	at dr.app.gui.chart.CategoryDensityPlot.setData(Unknown Source)
	at dr.app.gui.chart.CategoryDensityPlot.<init>(Unknown Source)
	at tracer.traces.DiscreteDensityPanel.setupTraces(Unknown Source)
	at tracer.traces.DiscreteDensityPanel.setTraces(Unknown Source)
	at tracer.traces.DensityPanel.setTraces(Unknown Source)
	at tracer.traces.TracePanel.setTraces(Unknown Source)
	at tracer.application.TracerFrame.statisticTableSelectionChanged(Unknown Source)
	at tracer.application.TracerFrame$4.valueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:154)
..etc..

**Comment by rambaut** [comment]
Have you pulled the latest changes? Here is what I get:
<img width="1312" alt="tmp" src="https://user-images.githubusercontent.com/686405/33139836-4d7e72d0-cfa6-11e7-97ab-be7adda5e7f5.png">

**Comment by bredelings** [comment]
Sorry, I thought I had, but apparently not.  Now I get that too. Maybe I just fetched them.
