### ISSUE TITLE
beast build bug to create tracer.jar

### ISSUE THREAD

**Issue by walterxie** [beast-dev/tracer#159]
It requires the dependency of "dr/inference/model".

Failed to load ch.randelshofer.quaqua.QuaquaLookAndFeel
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: dr/inference/model/GradientProvider
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:855)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:753)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at tracer.traces.ContinuousDensityPanel.createKDEPlot(Unknown Source)
	at tracer.traces.ContinuousDensityPanel.setupTraces(Unknown Source)
	at tracer.traces.TraceChartPanel.setupMainPanel(Unknown Source)

**Comment by walterxie** [comment]
This dependency is strange, but I fixed in beast https://github.com/beast-dev/beast-mcmc/commit/b634c2e86c5243805bfc51c361616873daff393f

**Comment by walterxie** [comment]
tracer.jar is updated
