### ISSUE TITLE
Exception of box plot

### ISSUE THREAD

**Issue by walterxie** [beast-dev/tracer#70]
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: There is no value sent to statistics calculation !
	at dr.inference.trace.TraceDistribution.initStatistics(TraceDistribution.java:235)
	at dr.inference.trace.TraceDistribution.<init>(TraceDistribution.java:48)
	at tracer.traces.JointDensityPanel.drawDiscreteBoxPlot(JointDensityPanel.java:358)
	at tracer.traces.JointDensityPanel.numericalPlot(JointDensityPanel.java:450)
	at tracer.traces.JointDensityPanel.setupTraces(JointDensityPanel.java:265)
	at tracer.traces.JointDensityPanel.setTraces(JointDensityPanel.java:189)
	at tracer.traces.TracePanel.setTraces(TracePanel.java:88)
	at tracer.application.TracerFrame.statisticTableSelectionChanged(TracerFrame.java:805)
	at tracer.application.TracerFrame$5.valueChanged(TracerFrame.java:232)

![screen shot 2017-04-04 at 5 10 30 pm](https://cloud.githubusercontent.com/assets/5743014/24642197/a373fd9e-1959-11e7-87b7-37455ce42cbd.png)

**Comment by walterxie** [comment]
```
if (sepValues[i].size() > 0) { // avoid RuntimeException: no value sent to statistics calculation
                TraceDistribution categoryTd = new TraceDistribution(sepValues[i], TraceType.REAL); // todo ?
                categoryTdMap.put(categoryValues.get(i), categoryTd);
            }
```

And use `for (Map.Entry<String, TraceDistribution> entry : categoryTdMap.entrySet()) {` because categoryTdMap.size < categoryValues.size if "samples only"
